services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    extends:
      file: compose.base-config.yml
      service: base
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - '${PORT:-8191}:8191'

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    extends:
      file: compose.base-config.yml
      service: base
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG_PATH}/qbittorrent_data:/config
      - ${HOST_TORRENT_PATH}:${CONTAINER_TORRENT_PATH}
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    user: ${PUID}:${PUID}
    volumes:
      - ${CONFIG_PATH}/profilarr_data:/config
