services:
  sonarr:
    extends:
      file: compose.base.yml
      service: base
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ${CONFIG_PATH}/sonar_data:/config
      - ${HOST_MEDIA_PATH}:${CONTAINER_MEDIA_PATH}
      - ${HOST_TORRENT_PATH}:/data/torrents
    ports:
      - 8989:8989

  radarr:
    extends:
      file: compose.base.yml
      service: base
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ${CONFIG_PATH}/radarr_data:/config
      - ${HOST_MEDIA_PATH}:${CONTAINER_MEDIA_PATH}
      - ${HOST_TORRENT_PATH}:/data/torrents
    ports:
      - 7878:7878

  bazarr:
    extends:
      file: compose.base.yml
      service: base
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - ${CONFIG_PATH}/bazarr_data:/config
      - ${HOST_MEDIA_PATH}/movies:/movies
      - ${HOST_MEDIA_PATH}/series:/series
      - ${HOST_MEDIA_PATH}/animes:/animes
    ports:
      - 6767:6767
