services:
  emby:
    extends:
      file: compose.base.yml
      service: base
    image: emby/embyserver
    container_name: embyserver
    network_mode: host
    environment:
      - UID=${PUID}
      - GID=100
      - GIDLIST=100
    volumes:
      - ${CONFIG_PATH}/emby_data:/config
      - ${HOST_MEDIA_PATH}/series:/mnt/series
      - ${HOST_MEDIA_PATH}/animes:/mnt/animes
      - ${HOST_MEDIA_PATH}/movies:/mnt/movies
    ports:
      - 8096:8096
    restart: on-failure
