name: media_server

services:
  sonarr:
    extends:
      file: compose.media.yml
      service: sonarr
  radarr:
    extends:
      file: compose.media.yml
      service: radarr
  bazarr:
    extends:
      file: compose.media.yml
      service: bazarr
  prowlarr:
    extends:
      file: compose.index.yml
      service: prowlarr
  jellyseerr:
    extends:
      file: compose.index.yml
      service: jellyseerr
  flaresolverr:
    extends:
      file: compose.tools.yml
      service: flaresolverr
  tautulli:
    extends:
      file: compose.tools.yml
      service: tautulli
