# services:
  # plex:
  #   image: lscr.io/linuxserver/plex:latest
  #   container_name: plex
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - VERSION=docker
  #   volumes:
  #     - ${CONFIG_PATH}/plex_data:/config
  #     - ${HOST_MEDIA_PATH}/series:/tv
  #     - ${HOST_MEDIA_PATH}/animes:/tv
  #     - ${HOST_MEDIA_PATH}/movies:/movies
  #   network_mode: host
  #   restart: unless-stopped
