name: media_server

services:
  jellyfin:
    extends:
      file: compose.players.yml
      service: jellyfin
  sonarr:
    extends:
      file: compose.servers.yml
      service: sonarr
  radarr:
    extends:
      file: compose.servers.yml
      service: radarr
  bazarr:
    extends:
      file: compose.servers.yml
      service: bazarr
  prowlarr:
    extends:
      file: compose.indexers.yml
      service: prowlarr
  flaresolverr:
    extends:
      file: compose.tools.yml
      service: flaresolverr
  jellyseerr:
    extends:
      file: compose.tools.yml
      service: jellyseerr
  qbittorrent:
    extends:
      file: compose.tools.yml
      service: qbittorrent
