name: media_server
services:
  # Baixa séries
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${CONFIG_PATH}/sonar_data
        target: /config
      - type: bind # optional
        source: ${SERIES_PATH}
        target: /tv
      - type: bind # optional
        source: ${TORRENT_PATH}
        target: /downloads
    networks:
      - gateway
    ports:
      - 8989:8989
    restart: unless-stopped

  # Baixa filmes
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${CONFIG_PATH}/radarr_data
        target: /config
      - type: bind # optional
        source: ${MOVIES_PATH}
        target: /movies
      - type: bind # optional
        source: ${TORRENT_PATH}
        target: /downloads
    networks:
      - gateway
    ports:
      - 7878:7878
    restart: unless-stopped

  # Baixa legendas
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${CONFIG_PATH}/bazarr_data
        target: /config
      - type: bind # optional
        source: ${MOVIES_PATH}
        target: /movies
      - type: bind # optional
        source: ${SERIES_PATH}
        target: /tv
    networks:
      - gateway
    ports:
      - 6767:6767
    restart: unless-stopped

  # Baixa livros
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${CONFIG_PATH}/readarr_data
        target: /config
      - type: bind # optional
        source: ${BOOKS_PATH}
        target: /books
      - type: bind # optional
        source: ${TORRENT_PATH}
        target: /downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  # Indexador de torrents
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - type: bind
        source: ${CONFIG_PATH}/prowlarr_data
        target: /config
    ports:
      - 9696:9696
    restart: unless-stopped

  # Solicitante de mídia
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - type: bind
        source: ${CONFIG_PATH}/overseerr_data
        target: /app/config
    restart: unless-stopped

  # Servidor de torrent
  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - WEBUI_PORT=8080
  #     - TORRENTING_PORT=6881
  #   volumes:
  #     - type: bind
  #       source: ${CONFIG_PATH}/qbittorrent_appdata
  #       target: /config
  #     - type: bind
  #       source: ${TORRENT_PATH}
  #       target: /downloads
  #   ports:
  #     - 8080:8080
  #     - 6881:6881
  #     - 6881:6881/udp
  #   restart: unless-stopped

  # Resolve captchas da CloudFlare
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

networks:
  gateway: {}
