name: media_server
services:
  # Baixa séries
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonar_data:/config
      - ${HOST_MEDIA_PATH}:${CONTAINER_MEDIA_PATH}
      - ${HOST_TORRENT_PATH}:/data/torrents
    networks:
      - gateway
    ports:
      - 8989:8989
    restart: unless-stopped

  # Baixa filmes
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr_data:/config
      - ${HOST_MEDIA_PATH}:${CONTAINER_MEDIA_PATH}
      - ${HOST_TORRENT_PATH}:/data/torrents
    networks:
      - gateway
    ports:
      - 7878:7878
    restart: unless-stopped

  # Baixa legendas
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/bazarr_data:/config
      - ${HOST_MEDIA_PATH}/movies:/movies
      - ${HOST_MEDIA_PATH}/series:/series
      - ${HOST_MEDIA_PATH}/animes:/animes
    networks:
      - gateway
    ports:
      - 6767:6767
    restart: unless-stopped

  # Baixa livros
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/readarr_data:/config
      - ${HOST_MEDIA_PATH}/books:/books
      - ${HOST_TORRENT_PATH}:/data/torrents
    ports:
      - 8787:8787
    restart: unless-stopped

  # Indexador de torrents
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr_data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # Solicitante de mídia
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/jellyseerr_data:/app/config
    restart: unless-stopped

  # Resolve captchas da CloudFlare
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

networks:
  gateway: {}
