services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Sao_Paulo
    volumes:
      - /Users/lucasnoman/Documents/Codes/Docker/Sonarr/sonar_data:/config
      - /Users/lucasnoman/Movies/TV/Series:/tv #optional
      - /Users/lucasnoman/TorrentDownload:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Sao_Paulo
      - AUTO_UPDATE=true #optional
    volumes:
      - /Users/lucasnoman/Documents/Codes/Docker/Sonarr/jackett_data:/config
      - /Users/lucasnoman/TorrentDownload:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Sao_Paulo
    volumes:
      - /Users/lucasnoman/Documents/Codes/Docker/Sonarr_Radarr/bazarr_data:/config
      - /Users/lucasnoman/Movies/TV/Movies:/movies #optional
      - /Users/lucasnoman/Movies/TV/Series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
